[feature/cumulative--10.0.0] AB#? - Closed Button Gap
saddlebackdev/react-cm-ui pull request #204
Opened 2020-09-08 23:06 UTC by alejosod

Button changes:
* Close Gaps
    * Need update the outline prop to extend outline and text colors - done
        * Change the “outlined” prop name to “outline” - done
    * Update color prop to use the theme.palette colors. - done
        * Color
            * Alert
                * Keep
            * Alternate
                * Keep the current color and rename to “Secondary”.
                * Delete Secondary style
            * Disable
                * Keep
            * Light
                * Delete
            * Outline
                * Delete
            * Primary
                * Keep
            * Secondary
                * Delete
            * Success
                * Keep
            * Transparent
                * Delete and create prop to handle the styling
            * Warning
                * Keep
        * Inverse
            * Delete the colors from that we are deleting form the color prop’s enum
        * Outlined
            * Change to outline.
            * Change label color to default black for all outline styles
            * Apple the changes being done int he color prop.
    * Need Touchscreen styling. - done
        * Add new boolean prop called “pill”.
        * Using the withStyles HOC style it.
* SCSS has already been converted to JSS - done
* Update the documentation page with the new code. - done
    * A good example ./docs/src/inputs/durationPicker/durationPicker.jsx

2020-09-09 14:53 UTC, morethanfire commented
@alejosod, it looks like there is a unit test check failing. Can you please commit a fix?

![image](https://user-images.githubusercontent.com/1100790/92615012-82ecba80-f271-11ea-975e-c322466b79f6.png)

2020-09-09 15:05 UTC, morethanfire requested changes
@alejosod, the PR is coming along. There a few changes I mentioned that need to take place and I have some concerns about what `.idea/` is and why we are introducing that to the repo

2020-09-09 15:05 UTC, morethanfire commented on src/inputs/button/button.jsx
>          const disable = disableProp || disabled;
Please remove `disabled` for all version 10.0.0 gap closures. It was a prop that was deprecated in version 9.

2020-09-09 15:05 UTC, morethanfire commented on src/inputs/button/button.jsx
> +                [classes.outlined]: !disable && outline,
I think that we should be able to have an outline and for the button to be disabled.

2020-09-09 15:05 UTC, morethanfire commented on src/inputs/button/button.jsx
> +                [classes.colorTransparent]: !disable && transparent,
I think that we should be able to have a transparent button and for the button to be disabled.

2020-09-09 15:05 UTC, morethanfire commented on src/inputs/button/__test__/button.test.js
> +});
Please test more than if Button renders. We can test the classes, events, etc.

2020-09-09 15:05 UTC, morethanfire commented on docs/src/inputs/button/buttonPillExample.jsx
> +export default ButtonPillExample;
Nice!

2020-09-09 15:05 UTC, morethanfire commented on docs/src/inputs/button/buttonOutlineExample.jsx
>              </Button>
I like it.

2020-09-09 15:05 UTC, morethanfire commented on docs/src/inputs/button/button.jsx
> +
Please use the new documentation components. We can get on a call to over this. Ping me when you can.

2020-09-09 16:27 UTC, alejosod commented on .gitignore
> +.idea/*
They are configuration for my IDE

2020-09-17 21:21 UTC, groberts314 commented
PR Review Checkpoint Meeting Thurs 2020-09-17.
* @alejosod ... Looks like a unit test is maybe failing?  Please check https://dev.azure.com/saddlebackchurch/b8a0d0bb-a4fe-48e3-9a60-2f1440145fc4/_build/results?buildId=20996
* @morethanfire Looks like some work was done to address your change requests.  Can you re-review?

2020-09-18 13:03 UTC, groberts314 commented
@alejosod @morethanfire Is this PR targeting `dev` correct?  Or should it be targeting `feature/cumulative--10.0.0`?

2020-10-08 16:29 UTC, morethanfire commented
Heads up @alejosod, I am going to start working on this branch to finish where you left off. 

This PR cannot be merged until PR #222 is merged. Probably, should wait on reviewing it until it is merged as well.

2020-11-03 00:28 UTC, merged