[feature/10.0.0/grid] AB#45651 & AB#45650: Mobile Stepper and Modal
saddlebackdev/react-cm-ui pull request #290
Opened 2021-05-07 20:55 UTC by oilywithraybans

2021-05-07 22:42 UTC, JLeeC approved these changes

2021-05-07 23:59 UTC, groberts314 approved these changes
Looks pretty good.  Just a couple of questions.

2021-05-07 23:59 UTC, groberts314 commented on src/navigation/mobileStepper/mobileStepper.jsx
> +     * See [CSS API](#css) below for more details.
This got copied from Material UI?
Should we replace this with an absolute URL that will work?

2021-05-07 23:59 UTC, groberts314 commented on src/navigation/mobileStepper/mobileStepper.jsx
> +     */
What's the point of `@ignore` directive on these comments?
Is this trying to tell you not to use `className` prop?

2021-05-19 12:26 UTC, fantaJinMode approved these changes
LGTM 💯

2021-05-19 13:36 UTC, IlyaRadinsky approved these changes

2021-05-19 17:54 UTC, cbrewer1689 commented
I merged PR #291 (Modal) into this PR. Can you guys please do some more reviews on this PR?

2021-05-19 18:26 UTC, groberts314 commented
@cbrewer1689 I am happy to re-review.

That having been said, #291 was fully approved by a couple of folks though prior to this merge, so no need to re-review changes already reviewed under that PR, right?  Any particular areas we should focus on in re-reviewing this PR at this point?

2021-05-19 18:28 UTC, groberts314 commented
Well hmm, maybe not.  I had thought it was reviewed and approved, but maybe I was mixing it up with this one.  NM ... I'll do the full re-review as soon as I can.

2021-05-19 22:03 UTC, groberts314 requested changes
Mostly looks good.  A few change requests here and there.

2021-05-20 16:11 UTC, cbrewer1689 commented on docs/src/dataDisplay/personCoreMilestones/api/api.jsx
> +import { default as rootDoc } from '!!@advclb/react-docgen-loader!react-cm-ui/surfaces/modal/modal';
I agree, weird.

2021-05-20 16:17 UTC, cbrewer1689 commented on docs/src/dataDisplay/personCoreMilestones/modal.jsx
> +import {
I sure hope this was a auto conflict fix, because if not, I may need to give up. 😄

2021-05-20 16:22 UTC, cbrewer1689 commented on src/surfaces/modal/modal.jsx
> +        this.onCloseBefore = this.onCloseBefore.bind(this);
I totally agree and even fight might myself, going back and forth on things such as this. I really would like to keep them grouped. Up to you though if you think this is blocking, I am not going to be hurt by it.

2021-05-20 16:24 UTC, cbrewer1689 commented on src/surfaces/modal/modal.jsx
> +    isFunction,
Fixed.

2021-05-20 16:24 UTC, cbrewer1689 commented on src/surfaces/modal/__test__/modalContent.test.js
> + * To run this test from the church-management/client folder, execute the following command:
Fixed.

2021-05-20 16:24 UTC, cbrewer1689 commented on src/surfaces/modal/__test__/modalActions.test.js
> + * To run this test from the church-management/client folder, execute the following command:
Fixed.

2021-05-20 16:25 UTC, cbrewer1689 commented on src/surfaces/modal/__test__/modal.test.js
> + * NOTE: This unit test is not done for the Modal, they were only introduced to test peices touched
Fixed.

2021-05-20 16:25 UTC, cbrewer1689 commented on src/surfaces/modal/__test__/modal.test.js
> + * To run this test from the church-management/client folder, execute the following command:
Fixed.

2021-05-20 16:25 UTC, cbrewer1689 commented on docs/src/surfaces/modal/api/api.jsx
> +import { default as rootDoc } from '!!@advclb/react-docgen-loader!react-cm-ui/dataDisplay/personCoreMilestones/personCoreMilestones';
Fixed.

2021-05-20 16:26 UTC, cbrewer1689 commented on docs/src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
> -import {
Fixed.

2021-05-20 16:26 UTC, cbrewer1689 commented on docs/src/dataDisplay/personCoreMilestones/modal.jsx
> +                        anchorLink="record-types"
Fixed.

2021-05-20 16:26 UTC, cbrewer1689 commented on docs/src/dataDisplay/personCoreMilestones/modal.jsx
> +function DocsButton(props) {
Fixed.

2021-05-20 16:26 UTC, cbrewer1689 commented on docs/src/dataDisplay/personCoreMilestones/modal.jsx
> +import {
Fixed.

2021-05-20 16:26 UTC, cbrewer1689 commented on docs/src/dataDisplay/personCoreMilestones/index.js
> +export { default } from './modal';
Fixed.

2021-05-20 16:26 UTC, cbrewer1689 commented on docs/src/dataDisplay/personCoreMilestones/api/api.jsx
> +import { default as rootDoc } from '!!@advclb/react-docgen-loader!react-cm-ui/surfaces/modal/modal';
Fixed.

2021-05-21 08:36 UTC, IlyaRadinsky approved these changes
Looks good to me.

2021-05-21 16:05 UTC, fantaJinMode commented on src/navigation/mobileStepper/mobileStepper.jsx
> +        ...otherProps
NAB: Could we add comma here?

2021-05-21 16:19 UTC, fantaJinMode approved these changes
LGTM :+1

2021-05-21 16:27 UTC, merged