[dev] [No PBI] - Fixing z-index conflict between Snackbar & Drawer Overlay
saddlebackdev/react-cm-ui pull request #468
Opened 2023-10-15 08:28 UTC by fantaJinMode

2023-10-17 19:56 UTC, War777 requested changes
I agreed with @groberts314 comment, let's try to call useStyles once please, let me know if you need help @fantaJinMode , thanks.

2023-10-18 11:12 UTC, fantaJinMode commented on src/feedback/snackbar/snackbar.jsx
>      const contentPropsClasses = useStyles(ContentProps);
Agreed, unnecessary to call `useStyles` twice. Thank you for pointing out. I have fixed that in this [commit link](https://github.com/saddlebackdev/react-cm-ui/pull/468/commits/04999f9bfff58c2f2fe171e019ef6f920aeb8bf1)
Please @groberts314  @War777 re-review it once.

2023-10-18 22:20 UTC, groberts314 approved these changes

2023-10-18 22:20 UTC, groberts314 commented on src/feedback/snackbar/snackbar.jsx
>      const contentPropsClasses = useStyles(ContentProps);
Looks better to me.

2023-10-19 02:15 UTC, War777 approved these changes

2023-10-19 14:08 UTC, merged